on:
    pull_request:
        types: [opened, reopened, ready_for_review, synchronize]
jobs:
    qodo_pr_review_job:
        name: Review by Qodo
        if: false
        runs-on: ubuntu-latest
        permissions: 
            pull-requests: write
        steps:
            - name: PR agent steps
              id: qodo-pr-agent
              uses: Codium-ai/pr-agent@main
              env:
                OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                GITHUB_ACTION_CONFIG.PR_ACTIONS: "opened,reopened,ready_for_review,review_requested,synchronize"

