on:
    pull_request:
        types: [opened, reopened, ready_for_review, synchronize]
jobs:
    pr_review_job:
        name: Review PR
        if: ${{ github.event.sender.type != 'Bot' }}
        runs-on: ubuntu-latest
        permissions: 
            pull-requests: write
        steps:
            - name: PR agent steps
              id: qodo-pr-agent
              uses: Codium-ai/pr-agent@main
              env:
                OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

